#!/bin/bash

set -ex

echo "### RUN build START: using buildx ###"
echo "Image Name: ${IMAGE_NAME} (Repo: ${DOCKER_REPO}, Tag: ${DOCKER_TAG})"
echo "Dockerfile Path/Name: ${DOCKERFILE_PATH}"
BUILD_PLATFORM="${BUILD_PLATFORM:-"linux/amd64,linux/arm64"}"
echo "Architectures=${BUILD_PLATFORM}"

docker buildx build --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
    --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
    --tag "${IMAGE_NAME}" --platform "${BUILD_PLATFORM}" --file "${DOCKERFILE_PATH}" --push .

echo "### RUN build END"
